### ISSUE TITLE
Guilds

### ISSUE THREAD

**Issue by GibsonGeorge** [JezzaR-The-Proto/RPGBot#4]
Suggestions:

* Allow both private and public guilds
* Make it so that only the guild leader (or a selected person/people) can give out gold/items
* Allow some form of guild communication, or at least a way or requesting stuff from the guild inventory

**Comment by JezzaR-The-Proto** [comment]
Will add to the v2.0 todo list

**Comment by JezzaR-The-Proto** [comment]
Private and public guilds are done. Guild leader can now only give out gold. There is a messaging system now. Done

**Comment by JezzaR-The-Proto** [comment]
Apparently not done the guild leader thing ok
