### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by GibsonGeorge** [JezzaR-The-Proto/RPGBot#5]
Suggestions:

* Make `rpg explore` actually change stats
* Add more ways to change specific stats of your character (training or something)
* ~~Balance everything~~

**Comment by JezzaR-The-Proto** [comment]
rpg explore does now change stats on the dev branch, training will be added to v2.0 todo list and equipping items.

**Comment by JezzaR-The-Proto** [comment]
Equipping is done, will be doing training soon maybe
